name: CI
on:
  push:
    branches: [main]
  pull_request: []
jobs:
  build-and-test:
    name: Python CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv (fast Python package manager)
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.6"

      - name: Install dependencies (via uv)
        run: uv sync --locked

      - name: Run Ruff (Lint & Format Check)
        run: uv run ruff check .

      - name: Run MyPy (Type Check)
        run: uv run mypy .

      - name: Run Tests (Pytest with Coverage)
        run: uv run pytest --cov=project_name --cov-report=term-missing --cov-fail-under=100
